1. Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np
matric1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matric2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(matric1+matric2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


2. Write a Python Program to Multiply Two Matrices?

In [3]:
import numpy as np
matric1 = np.array([[12, 7, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
matric2 = np.array([[5, 8, 1, 2],
                    [6, 7, 3, 0],
                    [4, 5, 9, 1]])

print(matric1.dot(matric2))

[[114 160  60  27]
 [ 74  97  73  14]
 [119 157 112  23]]


3. Write a Python Program to Transpose a Matrix?

In [5]:
import numpy as np
matric1 = np.array([[12,7],
                    [4 ,5],
                    [3 ,8]])
print(matric1.T)

[[12  4  3]
 [ 7  5  8]]


4. Write a Python Program to Sort Words in Alphabetic Order?

In [6]:
sentance = input("Enter the words: ")
words = [word.lower() for word in sentance.split()]
words.sort()

print("Sorted order of words:")
for word in words:
    print(word, end = ' ')
    

Enter the words: This is task from the Assignment
Sorted order of words:
assignment from is task the this 

Write a Python Program to Remove Punctuation From a String?

In [7]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

string = input("Enter the string: ")

outputString = ""

for char in string:
    if char not in punctuations:
        outputString += char
        
print(outputString)

Enter the string: Hello, World!!! <HTML> c++; {braces} \/!@##^&*()( Ending the string now.
Hello World HTML c++ braces  Ending the string now
